### ISSUE TITLE
Support reflectance data

### ISSUE THREAD

**Issue by mikepurvis** [ros-drivers/omron#1]
Need to understand how to best represent this data— either as a separate topic, or using [MultiEchoLaserScan](http://docs.ros.org/jade/api/sensor_msgs/html/msg/MultiEchoLaserScan.html).

**Comment by reinzor** [comment]
Addressed in https://github.com/ros-drivers/omron/pull/18

**Comment by reinzor** [comment]
Covered in https://github.com/ros-drivers/omron/pull/24
