### ISSUE TITLE
Release for noetic

### ISSUE THREAD

**Issue by Rayman** [ros-drivers/omron#27]
Hey, is it possible to release the omron driver for noetic? Are there any blocking issues for that?

**Comment by reinzor** [comment]
https://github.com/ros-drivers/odva_ethernetip has to be released first but it's not working on Noetic yet. I started a [branch](https://github.com/ros-drivers/odva_ethernetip/tree/fix/get-io-service-boost-noetic) a couple of months ago but I wasn't able to test this myself. If you could verify this works, I can create a Noetic release.

**Comment by reinzor** [comment]
Hmm, I see that branch is already merged. Could you verify this is working on `Noetic`? Both on the `kinetic-devel` branch?

**Comment by Rayman** [comment]
Everything seems to work. I'm running https://github.com/ros-drivers/odva_ethernetip/commit/a775b74fe1d2fd25447a58c64550058d533a47b0 with https://github.com/ros-drivers/omron/commit/0ce831ed9e27c5da3f8fa86f480d6b220ca01e06
```
rostopic hz /scan
subscribed to [/scan]
average rate: 12.857
	min: 0.078s max: 0.078s std dev: 0.00005s window: 13
average rate: 12.856
	min: 0.078s max: 0.078s std dev: 0.00005s window: 26
^Caverage rate: 12.856
	min: 0.078s max: 0.078s std dev: 0.00005s window: 36
```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by reinzor** [comment]
https://github.com/ros/rosdistro/pull/27500 `odva_ethernet_ip` release. I cannot release the `omron` driver yet because it complains that `odva_ethernet_ip` has not been released yet. 

```
Failed to resolve odva_ethernetip on ubuntu:focal with: Error running generator: Failed to resolve rosdep key 'odva_ethernetip', aborting.
odva_ethernetip is depended on by these packages: ['omron_os32c_driver']
<== Failed
Some of the dependencies for packages in this repository could not be resolved by rosdep.
```

Not sure if this is resolved when this PR gets accepted.

**Comment by Rayman** [comment]
They are gonna do a sync on monday, not sure if they will accept new packages before that date. 

https://discourse.ros.org/t/preparing-for-noetic-sync-2020-11-30/17574

**Comment by reinzor** [comment]
https://github.com/ros/rosdistro/pull/27543 ; will have to wait until next `noetic` sync

**Comment by reinzor** [comment]
merged

**Comment by mbed92** [comment]
What is the status of the Noetic release? According to [ROS packages](http://repositories.ros.org/status_page/ros_noetic_default.html?q=omron) the package is still missing.

**Comment by Rayman** [comment]
As far as I can see, the driver was released [see rosdistro](https://github.com/ros/rosdistro/blob/2a49cba1e5814939f16c901f84b75312b1b90b22/noetic/distribution.yaml#L4914) and in the release repo [here](https://github.com/ros-drivers-gbp/omron-release).

But for some reason, it's not showing up as released
http://repositories.ros.org/status_page/ros_noetic_default.html?q=omron

@reinzor what could have happened?

**Comment by reinzor** [comment]
I don't know why it doesn't have a binary release. `ros-noetic-odva-ethernetip` does exist and was released in the same way. 

However, when I look at the build page, it says aborted all the time ..

https://build.ros.org/job/Nbin_uF64__omron_os32c_driver__ubuntu_focal_amd64__binary/

I am on holiday now but I will try to look into this when I am back (in two weeks)

**Comment by mbed92** [comment]
Hi @reinzor. What's the status of the issue?
